title: howtogdpr.me
email: bodo@tasche.me
description: > # this means to ignore newlines until "baseurl:"
  Do you want to do a GDPR request and don't know how? This site
  wants to help.
url: "http://howtogdpr.me" # the base hostname & protocol for your site, e.g. http://example.com
github_username: howtogdpr

markdown: kramdown
highlighter: pygments
timezone: Europe/Berlin

paginate: 10
paginate_path: "/page/:num"

permalink: /:title/
emoji_dir: /css/emoji

collections:
  gdprs:
    output: true

exclude:
  - deploy.sh
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

gems:
  - jekyll-paginate
  - jekyll-sass-converter
  - jekyll-sitemap

sass:
  sass_dir: _sass

